# Project
# Mánagarmr
#
# 5. 12. 2019.
#
SOURCE_DIR=./src
BUILD_DIR=./build
OUT_DIR=./out

all: prepare
	cd $(SOURCE_DIR) && $(MAKE) all

prepare:
	mkdir -p $(BUILD_DIR) $(OUT_DIR)

.PHONY: prepare all
